# Pandas Assignment No.1 PIAIC53818

In [1]:
# Library Imports
import numpy as np
import pandas as pd
import glob
import matplotlib.pyplot as plt

##  PART 1: US Census

In [2]:
# HOW TO CLEAN DATA WITH PYTHON
# Cleaning US Census Data
    #You just got hired as a Data Analyst at the Census Bureau, 
    # which collects census data and creates interesting visualizations and insights from it.
    # The person who had your job before you left you all the data they had for the most recent census. 
    # It is in multiple csv files.
    # They didnâ€™t use pandas, they would just look through these csv files manually whenever they wanted to find something.
    # Sometimes they would copy and paste certain numbers into Excel to make charts.
    # The thought of it makes you shiver. This is not scalable or repeatable.
    # Your boss wants you to make some scatterplots and histograms by the end of the day. 
    # Can you get this data into pandas and into reasonable shape so that you can make these histograms?

#### Inspect the Data!

###### Step 01

In [3]:
# The first visualization your boss wants you to make is a scatterplot that shows 
    # average income in a state vs proportion of women in that state.
# Open some of the census csv files in the navigator. 
    # How are they named? 
    # What kind of information do they hold? 
    # Will they help us make this graph?

In [4]:
# visulizing few of the csv files given

In [5]:
df1 = pd.read_csv('states0.csv')
df1

,Unnamed: 0,State,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,Income,GenderPop
0,0,Alabama,4830620,3.7516156462584975%,61.878656462585%,31.25297619047618%,0.4532312925170065%,1.0502551020408146%,0.03435374149659865%,$43296.35860306644,2341093M_2489527F
1,1,Alaska,733375,5.909580838323351%,60.910179640718574%,2.8485029940119775%,16.39101796407186%,5.450299401197604%,1.0586826347305378%,$70354.74390243902,384160M_349215F
2,2,Arizona,6641928,29.565921052631502%,57.120000000000026%,3.8509868421052658%,4.35506578947368%,2.876578947368419%,0.16763157894736833%,$54207.82095490716,3299088M_3342840F
3,3,Arkansas,2958208,6.215474452554738%,71.13781021897813%,18.968759124087573%,0.5229197080291965%,1.1423357664233578%,0.14686131386861315%,$41935.63396778917,1451913M_1506295F
4,4,California,38421464,37.291874687968054%,40.21578881677474%,5.677396405391911%,0.40529206190713685%,13.052234148776776%,0.35141038442336353%,$67264.78230266465,19087135M_19334329F
5,5,Colorado,5278906,20.78438003220608%,69.89557165861504%,3.546376811594201%,0.5738325281803548%,2.661996779388082%,NaN,$64657.801787164906,2648667M_2630239F

In [6]:
df2 = pd.read_csv('states5.csv')
df2

,Unnamed: 0,State,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,Income,GenderPop
0,0,Missouri,6045448,4.037247838616718%,77.508069164265%,14.122118155619594%,0.36332853025936646%,1.6244956772334296%,0.10165706051873193%,$49763.98772563177,2964003M_3081445F
1,1,Montana,1014699,3.2688888888888896%,86.41555555555554%,0.4292592592592591%,7.0607407407407425%,0.5703703703703705%,0.07222222222222222%,$47645.682835820895,510163M_F
2,2,Nebraska,1869365,9.203759398496235%,81.13947368421056%,4.956203007518794%,0.8644736842105263%,1.8590225563909788%,0.05714285714285715%,$55916.469696969696,929606M_939759F
3,3,Nevada,2798636,27.100883652430046%,53.23932253313698%,7.739617083946994%,1.0871870397643593%,7.095729013254786%,0.5745213549337267%,$55526.525073746314,1407735M_1390901F
4,4,New Hampshire,1324201,3.3219178082191796%,91.31917808219184%,1.2277397260273974%,0.14280821917808229%,2.191438356164382%,0.016095890410958904%,$68728.8595890411,653484M_670717F
5,5,New Jersey,8904413,18.74950049950049%,56.488761238761285%,14.387862137862117%,0.11533466533466513%,8.159990009990018%,0.031318681318681325%,$76581.08341708542,4343027M_4561386F

In [7]:
df3 = pd.read_csv('states9.csv')
df3

,Unnamed: 0,State,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,Income,GenderPop
0,0,Utah,2903379,13.468376068376063%,79.40683760683764%,1.0179487179487194%,1.0813675213675222%,2.196068376068376%,0.8259829059829059%,$63488.91780821918,1459229M_1444150F
1,1,Vermont,626604,1.6092896174863391%,93.98306010928961%,0.9808743169398909%,0.301639344262295%,1.2387978142076501%,0.03060109289617486%,$55602.96721311475,308573M_318031F
2,2,Virginia,8256630,8.0110164981373%,63.271048430015945%,20.17599787120807%,0.21245343267695582%,5.455242150079845%,0.06471527408195847%,$72866.01341201717,4060948M_4195682F
3,3,Washington,6985464,11.140968858131506%,72.03840830449816%,3.384429065743947%,1.4107266435986163%,7.022006920415224%,0.609896193771627%,$64493.76768377254,3487725M_3497739F
4,4,West Virginia,1851420,1.290909090909089%,92.17623966942146%,3.6628099173553723%,0.15268595041322316%,0.6824380165289253%,0.02644628099173554%,$41437.11157024794,913631M_937789F
5,5,Wisconsin,5742117,6.683333333333334%,79.86400862068966%,8.195186781609202%,0.9536637931034483%,2.404238505747124%,0.020833333333333332%,$53898.889208633096,2851385M_2890732F